[profile.default]
  bytecode_hash = "none"
  evm_version = "cancun"
  ffi = true
  fs_permissions = [{ access = "read-write", path = ".forge-snapshots/" }]
  libs = ["lib"]
  optimizer_runs = 44444444
  out = "out"
  solc_version = "0.8.26"
  src = "src"


  # See more config options https://github.com/foundry-rs/foundry/tree/master/config
